name: android_OTA_make

on:
  watch:
    types: [started]
    
env:
  OLD_ROM_URL: https://dlsvr04.asus.com.cn/pub/ASUS/ZenFone/ZS620KL/UL-Z01R-WW-100.10.107.87-user.zip
  NEW_ROM_URL: https://dlsvr04.asus.com.cn/pub/ASUS/ZenFone/ZS620KL/UL-Z01R-WW-100.10.107.92-user.zip
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - name: Install Python Setuptools
      run: |
        cd ~
  
  
    - name: Initialization environment 
      run: |
        cd ~
        mkdir old-rom
        mkdir new-rom
        mkdir final-rom
        mkdir final
        sudo -E apt-get update
        sudo -E apt-get install wget python python-pip python3 python3-pip
        pip3 install setuptools
        pip3 install bsdiff4
        
    - name: Clean Up Disk Space
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean 
        
    - name: Clone the tools source code
      run: |
       cd ~
       git clone https://github.com/cjybyjk/OTA-maker.git 
  
    - name: Download the old ROM
      run: |
       cd ~
       cd old-rom
       wget -O old_rom.zip $OLD_ROM_URL
   
    - name: Download the new ROM
      run: |
       cd ~
       cd new-rom
       wget -O new_rom.zip $NEW_ROM_URL
    
    - name: make OTA ROM
      run: |
       cd ~
       cd OTA-maker
       python3 makeota.py ~/old-rom/old-rom.zip  ~/new-rom/new-rom.zip ~/final_rom
   
    - name: Zip OTA ROM
      run: |
          zip -r ~/final/OTA.zip ~/final_rom
    
    - name: Upload the OTA ROM to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/final/OTA.zip
