name: android_OTA_make

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  OLD_ROM_URL: https://bigota.d.miui.com/V11.0.2.0.PCMCNXM/miui_PINE_V11.0.2.0.PCMCNXM_fb68c600ed_9.0.zip
  NEW_ROM_URL: https://bigota.d.miui.com/V11.0.5.0.PCMCNXM/miui_PINE_V11.0.5.0.PCMCNXM_b3581f0e0c_9.0.zip
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        mkdir roms
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install python3.8
     
    - name: Clone the tools source code
      run: git clone https://github.com/cjybyjk/OTA-maker.git 
  
    - name: Download the old ROM
      uses: carlosperate/download-file-action@v1.0.2
      with:
         file-url: $OLD_ROM_URL
         file-name: OLD_ROM.zip
         location:  roms    
       
    
